import type { ProjectConfig, TemplateConfig } from "@/types/templates";

const sharedFilterControls = [
  {
    id: "year",
    label: "Year",
    type: "select" as const,
    options: ["2010", "2015", "2020", "2024"],
    defaultValue: "2024",
  },
  {
    id: "mode",
    label: "Mode",
    type: "select" as const,
    options: ["Transit", "Walking", "Driving", "Mixed"],
    defaultValue: "Transit",
  },
];

export const templateConfigs: TemplateConfig[] = [
  {
    slug: "choropleth-zoning-intensity",
    title: "Choropleth: Zoning Intensity",
    summary: "A straightforward choropleth map for neighborhood or parcel metrics with a strong legend and notes panel.",
    category: "choropleth",
    layout: "map-left",
    tags: ["choropleth", "zoning", "legend"],
    accent: "#0c7c59",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasFilterPanel: true,
    hasInspectPanel: true,
    styleType: "fill",
    metric: "Floor-area ratio capacity",
    location: "Chicago",
    datasetKey: "neighborhoods",
    filters: sharedFilterControls,
    notes: ["Best for zoning or capacity indices.", "Highlights a single primary metric."],
  },
  {
    slug: "choropleth-land-value",
    title: "Choropleth: Land Value Bands",
    summary: "A parcel or grid choropleth with banded classes and an overview panel tuned for land value stories.",
    category: "choropleth",
    layout: "focus-map",
    tags: ["land-value", "bands", "map-first"],
    accent: "#d95d39",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasInspectPanel: true,
    styleType: "fill",
    metric: "Land value index",
    location: "Japan",
    datasetKey: "neighborhoods",
    notes: ["Good flagship starter layout.", "Minimal chrome keeps the map prominent."],
  },
  {
    slug: "choropleth-bivariate-access",
    title: "Choropleth: Access vs Capacity",
    summary: "A bivariate choropleth shell for showing the overlap between access and zoning or land-use opportunity.",
    category: "choropleth",
    layout: "map-right",
    tags: ["bivariate", "access", "capacity"],
    accent: "#275d8c",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasFilterPanel: true,
    hasInspectPanel: true,
    styleType: "fill",
    metric: "Transit access vs zoning capacity",
    location: "Tokyo",
    datasetKey: "neighborhoods",
    filters: sharedFilterControls,
    notes: ["Useful for explaining tradeoffs.", "Legend can be replaced later with a 3x3 matrix."],
  },
  {
    slug: "time-slider-urban-growth",
    title: "Time Slider: Urban Growth",
    summary: "A single-map time scrubber template for yearly land-cover or development intensity change.",
    category: "time-slider",
    layout: "map-left",
    tags: ["time", "growth", "yearly"],
    accent: "#0f766e",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasTimeSlider: true,
    hasFilterPanel: true,
    styleType: "fill",
    metric: "Built-up intensity",
    location: "Pearl River Delta",
    datasetKey: "neighborhoods",
    filters: sharedFilterControls,
    notes: ["Assumes data sorted by year.", "Works well for yearly snapshots."],
  },
  {
    slug: "time-slider-historical-osm",
    title: "Time Slider: Historical OSM Layers",
    summary: "A map-focused timeline for changes in mapped renewable energy or transport features over time.",
    category: "time-slider",
    layout: "stacked",
    tags: ["osm-history", "renewables", "timeline"],
    accent: "#7f5539",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasTimeSlider: true,
    hasInspectPanel: true,
    styleType: "circle",
    metric: "Mapped assets by year",
    location: "China",
    datasetKey: "stations",
    notes: ["Best when features arrive year-by-year.", "Click inspection works well with sparse points."],
  },
  {
    slug: "time-slider-raster-index",
    title: "Time Slider: Raster Index Story",
    summary: "A raster-ready time template designed for future land-cover or population intensity tiles.",
    category: "time-slider",
    layout: "focus-map",
    tags: ["raster", "population", "land-cover"],
    accent: "#6b8e23",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasTimeSlider: true,
    styleType: "raster",
    metric: "Land-use intensity raster",
    location: "Metro Region",
    datasetKey: "neighborhoods",
    notes: ["Uses vector demo data now, but ready for raster tiles later.", "Good placeholder for COG workflows."],
  },
  {
    slug: "before-after-station-areas",
    title: "Before/After: Station Area Change",
    summary: "A swipe comparison template for showing policy or development change around rail stations.",
    category: "before-after",
    layout: "comparison",
    tags: ["swipe", "stations", "policy-change"],
    accent: "#9a3412",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasCompareSlider: true,
    hasInspectPanel: true,
    styleType: "fill",
    metric: "Before/after zoning index",
    location: "Japan",
    datasetKey: "neighborhoods",
    notes: ["Ideal for regulation or redevelopment narratives.", "Works well with the flagship project."],
  },
  {
    slug: "before-after-raster-change",
    title: "Before/After: Raster Change Lens",
    summary: "A compare view designed for land cover or intensity rasters, with room for concise captions.",
    category: "before-after",
    layout: "comparison",
    tags: ["raster", "change-detection", "swipe"],
    accent: "#4c6a92",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasCompareSlider: true,
    styleType: "raster",
    metric: "Land cover change",
    location: "Regional Study Area",
    datasetKey: "neighborhoods",
    notes: ["Useful once raster tiles are uploaded.", "Easy to adapt to population surfaces."],
  },
  {
    slug: "before-after-policy-compare",
    title: "Before/After: Policy Scenario Overlay",
    summary: "A compare shell for plan alternatives, draft zoning, or speculative redevelopment cases.",
    category: "before-after",
    layout: "map-right",
    tags: ["scenario", "policy", "alternatives"],
    accent: "#a16207",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasCompareSlider: true,
    hasFilterPanel: true,
    styleType: "fill",
    metric: "Scenario suitability score",
    location: "Chicago",
    datasetKey: "neighborhoods",
    filters: sharedFilterControls,
    notes: ["Good for narrative policy testing.", "Can later branch into multi-scenario toggles."],
  },
  {
    slug: "filter-panel-zoning-explorer",
    title: "Filter Panel: Zoning Explorer",
    summary: "A practical template with multiple filters for land use, built form, and station access.",
    category: "filter-panel",
    layout: "map-left",
    tags: ["filters", "explorer", "zoning"],
    accent: "#2c5282",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasFilterPanel: true,
    hasInspectPanel: true,
    styleType: "fill",
    metric: "Filtered neighborhood capacity",
    location: "Chicago",
    datasetKey: "neighborhoods",
    filters: [
      ...sharedFilterControls,
      {
        id: "distance",
        label: "Station distance",
        type: "range",
        min: 0,
        max: 2000,
        step: 100,
        defaultValue: 800,
      },
    ],
    notes: ["Designed for exploratory work.", "Strong match for planning-review style projects."],
  },
  {
    slug: "filter-panel-station-rings",
    title: "Filter Panel: Station Rings",
    summary: "A ring-focused filtering template for comparing catchments around railway stations.",
    category: "filter-panel",
    layout: "stacked",
    tags: ["rings", "stations", "analytics"],
    accent: "#0c7c59",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasFilterPanel: true,
    hasExtentAnalysis: true,
    styleType: "circle",
    metric: "Value by distance ring",
    location: "Japan",
    datasetKey: "stations",
    chartTitle: "Distance ring profile",
    chartDescription: "Summaries are triggered manually so heavier analyses stay intentional.",
    chartSeries: [
      { key: "housing", label: "Housing capacity", color: "#0c7c59" },
      { key: "value", label: "Land value", color: "#d95d39" },
    ],
    filters: [
      {
        id: "distance",
        label: "Ring size (m)",
        type: "select",
        options: ["250", "500", "800", "1200"],
        defaultValue: "500",
      },
      {
        id: "stationClass",
        label: "Station class",
        type: "select",
        options: ["Local", "Rapid", "Hub"],
        defaultValue: "Hub",
      },
    ],
    notes: ["Flagship-friendly analytics template.", "Manual analysis button keeps the interaction clear."],
  },
  {
    slug: "filter-panel-point-clusters",
    title: "Filter Panel: Point Cluster Explorer",
    summary: "A point-focused explorer for project portfolios involving stations, permits, or renewable assets.",
    category: "filter-panel",
    layout: "map-right",
    tags: ["points", "clusters", "filters"],
    accent: "#6d28d9",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasFilterPanel: true,
    hasInspectPanel: true,
    styleType: "circle",
    metric: "Filtered project points",
    location: "National Sample",
    datasetKey: "stations",
    filters: sharedFilterControls,
    notes: ["Useful for sparse point datasets.", "Adapts well to future asset maps."],
  },
  {
    slug: "extent-summary-neighborhood",
    title: "Active Extent: Neighborhood Summary",
    summary: "A classic map plus chart template that summarizes what falls inside the current viewport.",
    category: "extent-analytics",
    layout: "map-left",
    tags: ["extent", "summary", "charts"],
    accent: "#0e7490",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasExtentAnalysis: true,
    hasFilterPanel: true,
    styleType: "fill",
    metric: "Neighborhood indicators",
    location: "Chicago",
    datasetKey: "neighborhoods",
    chartTitle: "Current view summary",
    chartDescription: "Use the button to calculate metrics inside the visible map window.",
    chartSeries: [
      { key: "capacity", label: "Capacity", color: "#0e7490" },
      { key: "population", label: "Population", color: "#f97316" },
    ],
    filters: sharedFilterControls,
    notes: ["Great for urban mirror ideas.", "Manual trigger keeps performance predictable."],
  },
  {
    slug: "extent-summary-station-access",
    title: "Active Extent: Station Access Charts",
    summary: "An extent-driven chart panel focused on station counts, service levels, and access sheds.",
    category: "extent-analytics",
    layout: "stacked",
    tags: ["extent", "stations", "access"],
    accent: "#047857",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasExtentAnalysis: true,
    hasInspectPanel: true,
    styleType: "circle",
    metric: "Stations in current view",
    location: "Japan",
    datasetKey: "stations",
    chartTitle: "Stations in frame",
    chartDescription: "Useful when the map window itself is the unit of analysis.",
    chartSeries: [
      { key: "ridership", label: "Ridership proxy", color: "#047857" },
      { key: "jobs", label: "Jobs access", color: "#7c3aed" },
    ],
    notes: ["Works well with point datasets.", "Easy to adapt to station-area reporting."],
  },
  {
    slug: "extent-summary-urban-mirror",
    title: "Active Extent: Urban Mirror",
    summary: "A denser analytics dashboard for current-window land use, cover, and activity summaries.",
    category: "extent-analytics",
    layout: "dual",
    tags: ["urban-mirror", "dashboard", "current-window"],
    accent: "#be123c",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasExtentAnalysis: true,
    hasFilterPanel: true,
    styleType: "hex",
    metric: "Land-use composition",
    location: "Metro Core",
    datasetKey: "hexgrid",
    chartTitle: "Current extent analytics",
    chartDescription: "Pairs a dense map with multiple small summaries.",
    chartSeries: [
      { key: "mixedUse", label: "Mixed use", color: "#be123c" },
      { key: "residential", label: "Residential", color: "#2563eb" },
    ],
    filters: sharedFilterControls,
    notes: ["Good target for your urban mirror concept.", "Hex or raster layers both fit here."],
  },
  {
    slug: "inspect-parcel-detail",
    title: "Inspect: Parcel Detail Panel",
    summary: "A click-to-inspect layout with a concise side panel for feature attributes and notes.",
    category: "inspect",
    layout: "map-left",
    tags: ["inspect", "parcels", "detail"],
    accent: "#8b5cf6",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasInspectPanel: true,
    styleType: "fill",
    metric: "Selected parcel profile",
    location: "Tokyo",
    datasetKey: "neighborhoods",
    notes: ["Best when feature attributes matter.", "Keeps charts optional."],
  },
  {
    slug: "inspect-station-profile",
    title: "Inspect: Station Profile Card",
    summary: "A point-inspection page that emphasizes one selected feature and its immediate context.",
    category: "inspect",
    layout: "map-right",
    tags: ["station", "profile", "inspect"],
    accent: "#c2410c",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasInspectPanel: true,
    hasExtentAnalysis: true,
    styleType: "circle",
    metric: "Selected station profile",
    location: "Japan",
    datasetKey: "stations",
    chartTitle: "Selected station context",
    chartDescription: "Pair clicked features with a short chart or comparison block.",
    chartSeries: [
      { key: "boardings", label: "Boardings", color: "#c2410c" },
      { key: "landValue", label: "Land value", color: "#15803d" },
    ],
    notes: ["A strong template for flagship case-study detail.", "Works with station rings too."],
  },
  {
    slug: "inspect-hex-cell",
    title: "Inspect: Hex Cell Readout",
    summary: "A compact inspection page for hex cells or gridded summaries with just enough metadata.",
    category: "inspect",
    layout: "focus-map",
    tags: ["hex", "grid", "inspect"],
    accent: "#0891b2",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasInspectPanel: true,
    styleType: "hex",
    metric: "Selected grid summary",
    location: "Regional Surface",
    datasetKey: "hexgrid",
    notes: ["Useful for density and gridded surfaces.", "Pairs well with a legend-focused UI."],
  },
  {
    slug: "sync-maps-baseline-vs-scenario",
    title: "Synced Maps: Baseline vs Scenario",
    summary: "Two synchronized maps for comparing a current condition against a scenario or policy layer.",
    category: "sync-maps",
    layout: "dual",
    tags: ["sync", "scenario", "compare"],
    accent: "#1d4ed8",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasSyncedMaps: true,
    hasInspectPanel: true,
    styleType: "fill",
    metric: "Scenario comparison",
    location: "Chicago",
    datasetKey: "neighborhoods",
    notes: ["Good for side-by-side narratives.", "Links panning and zooming."],
  },
  {
    slug: "sync-maps-city-comparison",
    title: "Synced Maps: City Comparison",
    summary: "A paired-map template for comparing urban patterns across multiple cities at the same scale.",
    category: "sync-maps",
    layout: "dual",
    tags: ["city-comparison", "sync", "scale"],
    accent: "#7c2d12",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasSyncedMaps: true,
    styleType: "circle",
    metric: "Building volume vs flow",
    location: "Shanghai / Guangzhou / Beijing / Chongqing",
    datasetKey: "stations",
    notes: ["Good fit for your scaling relationship work.", "Can be extended to a 2x2 small-multiple grid later."],
  },
  {
    slug: "sync-maps-zoning-land-value",
    title: "Synced Maps: Zoning and Land Value",
    summary: "A paired flagship template where one view shows zoning and the other shows land value or access.",
    category: "sync-maps",
    layout: "dual",
    tags: ["japan", "zoning", "land-value"],
    accent: "#0c7c59",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasSyncedMaps: true,
    hasExtentAnalysis: true,
    styleType: "fill",
    metric: "Zoning and value comparison",
    location: "Japan",
    datasetKey: "neighborhoods",
    chartTitle: "Cross-map comparison",
    chartDescription: "Use synchronized views to compare two related but different surfaces.",
    chartSeries: [
      { key: "zoning", label: "Zoning", color: "#0c7c59" },
      { key: "value", label: "Land value", color: "#d95d39" },
    ],
    notes: ["Strong flagship companion template.", "Useful for visually linking related surfaces."],
  },
  {
    slug: "density-hexbin-neighborhood",
    title: "Density: Hexbin Neighborhood Surface",
    summary: "A hexbin-style density view for summarizing activity, permits, or intensity across space.",
    category: "density",
    layout: "focus-map",
    tags: ["hexbin", "density", "surface"],
    accent: "#9333ea",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasDensityOverlay: true,
    hasInspectPanel: true,
    styleType: "hex",
    metric: "Hexbin density",
    location: "Metro Region",
    datasetKey: "hexgrid",
    notes: ["Good default density template.", "Hex cells are easy to read in planning contexts."],
  },
  {
    slug: "density-heatmap-assets",
    title: "Density: Heatmap of Assets",
    summary: "A point heatmap shell for dense observations such as energy assets, permits, or POIs.",
    category: "density",
    layout: "map-left",
    tags: ["heatmap", "assets", "points"],
    accent: "#ea580c",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasDensityOverlay: true,
    hasFilterPanel: true,
    styleType: "heatmap",
    metric: "Point density",
    location: "China",
    datasetKey: "stations",
    filters: sharedFilterControls,
    notes: ["Especially useful for renewable energy story maps.", "Can later switch between heatmap and points."],
  },
  {
    slug: "density-cluster-vs-surface",
    title: "Density: Clusters and Surface",
    summary: "A hybrid density page that lets you switch between clusters, hex cells, and a smoother surface.",
    category: "density",
    layout: "stacked",
    tags: ["hybrid", "clusters", "surface"],
    accent: "#0369a1",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasDensityOverlay: true,
    hasFilterPanel: true,
    hasInspectPanel: true,
    styleType: "circle",
    metric: "Density mode comparison",
    location: "Metro Sample",
    datasetKey: "stations",
    filters: [
      {
        id: "density-mode",
        label: "Density mode",
        type: "select",
        options: ["Clusters", "Heatmap", "Hexbin"],
        defaultValue: "Clusters",
      },
    ],
    notes: ["Useful when you want to compare different visual encodings.", "Good teaching template too."],
  },
  {
    slug: "choropleth-station-rings",
    title: "Choropleth: Station Ring Bands",
    summary: "A banded polygon template focused on walk rings or service areas around transit stations.",
    category: "choropleth",
    layout: "map-left",
    tags: ["rings", "transit", "service-area"],
    accent: "#15803d",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasFilterPanel: true,
    hasExtentAnalysis: true,
    styleType: "fill",
    metric: "Station area opportunity",
    location: "Japan",
    datasetKey: "neighborhoods",
    chartTitle: "Ring summary",
    chartDescription: "Compare capacity or value by ring band.",
    chartSeries: [
      { key: "inner", label: "Inner ring", color: "#15803d" },
      { key: "outer", label: "Outer ring", color: "#ca8a04" },
    ],
    filters: sharedFilterControls,
    notes: ["A strong bridge between choropleths and station analytics.", "Useful for the flagship project."],
  },
  {
    slug: "time-slider-city-comparison",
    title: "Time Slider: Multi-City Comparison",
    summary: "A yearly slider template with supporting notes for comparing how multiple cities evolve over time.",
    category: "time-slider",
    layout: "map-right",
    tags: ["multi-city", "time", "comparison"],
    accent: "#b91c1c",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasTimeSlider: true,
    hasFilterPanel: true,
    styleType: "circle",
    metric: "Annual urban indicator",
    location: "China major cities",
    datasetKey: "stations",
    filters: [
      {
        id: "city",
        label: "City",
        type: "select",
        options: ["Shanghai", "Guangzhou", "Beijing", "Chongqing"],
        defaultValue: "Shanghai",
      },
      {
        id: "year",
        label: "Year",
        type: "select",
        options: ["2010", "2014", "2018", "2022", "2024"],
        defaultValue: "2024",
      },
    ],
    notes: ["Fits your scaling project well.", "Useful when year is the main organizing index."],
  },
  {
    slug: "extent-summary-raster-zonal",
    title: "Active Extent: Raster Zonal Stats",
    summary: "A raster-oriented template for future zonal summaries inside the visible map extent.",
    category: "extent-analytics",
    layout: "map-right",
    tags: ["raster", "extent", "zonal-stats"],
    accent: "#4338ca",
    basemaps: ["osm", "positron", "satellite"],
    hasTransitToggle: true,
    hasExtentAnalysis: true,
    styleType: "raster",
    metric: "Raster zonal metrics",
    location: "Regional Surface",
    datasetKey: "hexgrid",
    chartTitle: "Raster summary",
    chartDescription: "Placeholder for future population or land-cover summaries.",
    chartSeries: [
      { key: "mean", label: "Mean intensity", color: "#4338ca" },
      { key: "peak", label: "Peak intensity", color: "#16a34a" },
    ],
    notes: ["Useful once raster preprocessing is ready.", "The UI pattern is already in place."],
  },
];

export const flagshipProject: ProjectConfig = {
  slug: "japan-zoning-land-value",
  title: "Interactive Japanese Zoning and Land Value Map",
  subtitle: "A flagship project pairing zoning, land value, and station-distance analytics.",
  intro:
    "This prototype project page highlights map-centric comparison, distance-ring analytics, and feature inspection for Japanese station areas.",
  location: "Japan",
  heroTemplateSlug: "filter-panel-station-rings",
  supportingTemplateSlugs: [
    "choropleth-land-value",
    "before-after-station-areas",
    "sync-maps-zoning-land-value",
    "inspect-station-profile",
  ],
  callouts: [
    "Distance-ring charts are manually triggered from the current map view.",
    "The template is built to swap in your real zoning, land value, and station datasets later.",
    "Transit overlay is left as a clean placeholder when you want to add a custom network layer.",
  ],
};

export const upcomingProjects: ProjectConfig[] = [
  {
    slug: "chicago-zoning-capacity",
    title: "Zoning Capacity of Neighborhoods in Chicago",
    subtitle: "Neighborhood capacity mapping inspired by planning and housing analysis work.",
    intro: "A project shell for zoning capacity, neighborhood comparison, and policy scenarios.",
    location: "Chicago",
    heroTemplateSlug: "choropleth-zoning-intensity",
    supportingTemplateSlugs: ["filter-panel-zoning-explorer", "sync-maps-baseline-vs-scenario"],
    callouts: ["Good fit for capacity choropleths and scenario maps."],
  },
  {
    slug: "china-scaling-relationship",
    title: "Building Volume and Passenger Flow in Major Chinese Cities",
    subtitle: "A comparison-oriented shell for Shanghai, Guangzhou, Beijing, and Chongqing.",
    intro: "This project shell emphasizes synchronized city comparisons and simple time filtering.",
    location: "China",
    heroTemplateSlug: "sync-maps-city-comparison",
    supportingTemplateSlugs: ["time-slider-city-comparison", "extent-summary-station-access"],
    callouts: ["Supports multi-city and point-based analytics."],
  },
  {
    slug: "urban-mirror-land-use",
    title: "Urban Mirror With Land-Use Analytics",
    subtitle: "An active-window analytics pattern for current map extent summaries.",
    intro: "This project shell focuses on manual current-window analysis and summary charts.",
    location: "Metro Core",
    heroTemplateSlug: "extent-summary-urban-mirror",
    supportingTemplateSlugs: ["extent-summary-neighborhood", "inspect-hex-cell"],
    callouts: ["Manual trigger helps keep extent analytics legible."],
  },
  {
    slug: "china-renewable-growth",
    title: "Growth of Renewable Energy in China From Historical OSM Data",
    subtitle: "A timeline and density-focused shell for historical point and surface layers.",
    intro: "This project shell is ready for yearly OSM-derived assets once your time data is assembled.",
    location: "China",
    heroTemplateSlug: "time-slider-historical-osm",
    supportingTemplateSlugs: ["density-heatmap-assets", "before-after-raster-change"],
    callouts: ["Assumes time data will be organized by year."],
  },
];

export const templateCategories = [
  { key: "choropleth", label: "Choropleths" },
  { key: "time-slider", label: "Time Sliders" },
  { key: "before-after", label: "Before / After" },
  { key: "filter-panel", label: "Filter Panels" },
  { key: "extent-analytics", label: "Extent Analytics" },
  { key: "inspect", label: "Feature Inspection" },
  { key: "sync-maps", label: "Synced Maps" },
  { key: "density", label: "Density / Hexbin" },
] as const;
